### ISSUE TITLE
Get data from BG Ponder Indexer

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/sandgarden.buidlguidl.com#5]
We have deployed https://github.com/BuidlGuidl/bg-ponder-indexer to https://bg-ponder-indexer-production.up.railway.app/.

It indexes the events coming from all the cohorts and saves it to a PostgreSQL database. We can get _some_ cohort data (builders, withdraws) from it, so loading times will be way faster than using the event hooks.

- Let's use it on the projects & member page.
- For withdraws, we have to query the old contract too (0x2eA63c9C9C114ae85b1027697A906420a23e8572)

Regarding what library to use, it seems that [URLQ](https://formidable.com/open-source/urql/) is a good alternative to Apollo, but open to both!

**Comment by technophile-04** [comment]
planning to tackle this tomorrow 🙌 but if anyone wants to tackle please feel free to...happy to collaborate!

**Comment by carletex** [comment]
Merged #6 which fetches the withdrawal events (super fast)

Let's create another PR to fetch the builder data.
